# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mwin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MWin(object):
    def setupUi(self, MWin):
        MWin.setObjectName("MWin")
        MWin.resize(960, 540)
        MWin.setMinimumSize(QtCore.QSize(960, 540))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        MWin.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/bililogo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MWin.setWindowIcon(icon)
        MWin.setIconSize(QtCore.QSize(35, 35))
        self.centralWidget = QtWidgets.QWidget(MWin)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.centralWidget.setFont(font)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.home.setFont(font)
        self.home.setObjectName("home")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.home)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout2 = QtWidgets.QHBoxLayout()
        self.layout2.setSpacing(6)
        self.layout2.setObjectName("layout2")
        self.logo = QtWidgets.QLabel(self.home)
        self.logo.setMinimumSize(QtCore.QSize(220, 105))
        self.logo.setMaximumSize(QtCore.QSize(220, 105))
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.layout2.addWidget(self.logo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.layout2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.layout1 = QtWidgets.QHBoxLayout()
        self.layout1.setSpacing(6)
        self.layout1.setObjectName("layout1")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout1.addItem(spacerItem2)
        self.comboBoxHome = QtWidgets.QComboBox(self.home)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.comboBoxHome.setFont(font)
        self.comboBoxHome.setObjectName("comboBoxHome")
        self.comboBoxHome.addItem("")
        self.comboBoxHome.addItem("")
        self.layout1.addWidget(self.comboBoxHome)
        self.lineEditHome = QtWidgets.QLineEdit(self.home)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.lineEditHome.setFont(font)
        self.lineEditHome.setObjectName("lineEditHome")
        self.layout1.addWidget(self.lineEditHome)
        self.searchBtn = QtWidgets.QToolButton(self.home)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.searchBtn.setFont(font)
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchBtn.setObjectName("searchBtn")
        self.layout1.addWidget(self.searchBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout1.addItem(spacerItem3)
        self.layout1.setStretch(0, 1)
        self.layout1.setStretch(1, 1)
        self.layout1.setStretch(2, 4)
        self.layout1.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.layout1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 218, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 3)
        self.verticalLayout_2.setStretch(3, 8)
        self.stackedWidget.addWidget(self.home)
        self.vpage = QtWidgets.QWidget()
        self.vpage.setObjectName("vpage")
        self.stackedWidget.addWidget(self.vpage)
        self.ppage = QtWidgets.QWidget()
        self.ppage.setObjectName("ppage")
        self.stackedWidget.addWidget(self.ppage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MWin.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MWin)
        self.statusBar.setObjectName("statusBar")
        MWin.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MWin)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 960, 23))
        self.menuBar.setObjectName("menuBar")
        self.Setting = QtWidgets.QMenu(self.menuBar)
        self.Setting.setObjectName("Setting")
        self.About = QtWidgets.QMenu(self.menuBar)
        self.About.setObjectName("About")
        MWin.setMenuBar(self.menuBar)
        self.minSizeAction = QtWidgets.QAction(MWin)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minSizeAction.setIcon(icon1)
        self.minSizeAction.setObjectName("minSizeAction")
        self.bgiPathAction = QtWidgets.QAction(MWin)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/bgm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bgiPathAction.setIcon(icon2)
        self.bgiPathAction.setObjectName("bgiPathAction")
        self.authorAction = QtWidgets.QAction(MWin)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/me.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.authorAction.setIcon(icon3)
        self.authorAction.setObjectName("authorAction")
        self.appAction = QtWidgets.QAction(MWin)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appAction.setIcon(icon4)
        self.appAction.setObjectName("appAction")
        self.Setting.addAction(self.minSizeAction)
        self.Setting.addAction(self.bgiPathAction)
        self.About.addAction(self.authorAction)
        self.About.addAction(self.appAction)
        self.menuBar.addAction(self.Setting.menuAction())
        self.menuBar.addAction(self.About.menuAction())

        self.retranslateUi(MWin)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MWin)

    def retranslateUi(self, MWin):
        _translate = QtCore.QCoreApplication.translate
        MWin.setWindowTitle(_translate("MWin", "嗶哩嗶哩盒子©Lewis Tian"))
        self.comboBoxHome.setItemText(0, _translate("MWin", "视频"))
        self.comboBoxHome.setItemText(1, _translate("MWin", "图片"))
        self.searchBtn.setToolTip(_translate("MWin", "搜索"))
        self.searchBtn.setText(_translate("MWin", "搜索"))
        self.searchBtn.setShortcut(_translate("MWin", "Return"))
        self.Setting.setTitle(_translate("MWin", "设置"))
        self.About.setTitle(_translate("MWin", "关于"))
        self.minSizeAction.setText(_translate("MWin", "窗口最小尺寸"))
        self.minSizeAction.setShortcut(_translate("MWin", "Ctrl+M"))
        self.bgiPathAction.setText(_translate("MWin", "背景图片"))
        self.bgiPathAction.setShortcut(_translate("MWin", "Ctrl+B"))
        self.authorAction.setText(_translate("MWin", "开发者"))
        self.authorAction.setShortcut(_translate("MWin", "Alt+A"))
        self.appAction.setText(_translate("MWin", "本程序"))
        self.appAction.setShortcut(_translate("MWin", "Shift+A"))

import res_rc
