# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mwin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MWin(object):
    def setupUi(self, MWin):
        MWin.setObjectName("MWin")
        MWin.resize(960, 540)
        MWin.setMinimumSize(QtCore.QSize(960, 540))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        MWin.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/bililogo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MWin.setWindowIcon(icon)
        MWin.setIconSize(QtCore.QSize(35, 35))
        self.centralWidget = QtWidgets.QWidget(MWin)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.centralWidget.setFont(font)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.home.setFont(font)
        self.home.setObjectName("home")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.home)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout2 = QtWidgets.QHBoxLayout()
        self.layout2.setSpacing(6)
        self.layout2.setObjectName("layout2")
        self.logo = QtWidgets.QLabel(self.home)
        self.logo.setMinimumSize(QtCore.QSize(220, 105))
        self.logo.setMaximumSize(QtCore.QSize(220, 105))
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.layout2.addWidget(self.logo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.layout2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.layout1 = QtWidgets.QHBoxLayout()
        self.layout1.setSpacing(6)
        self.layout1.setObjectName("layout1")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout1.addItem(spacerItem2)
        self.comboBoxHome = QtWidgets.QComboBox(self.home)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.comboBoxHome.setFont(font)
        self.comboBoxHome.setObjectName("comboBoxHome")
        self.comboBoxHome.addItem("")
        self.comboBoxHome.addItem("")
        self.layout1.addWidget(self.comboBoxHome)
        self.lineEditHome = QtWidgets.QLineEdit(self.home)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.lineEditHome.setFont(font)
        self.lineEditHome.setObjectName("lineEditHome")
        self.layout1.addWidget(self.lineEditHome)
        self.searchBtn = QtWidgets.QToolButton(self.home)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.searchBtn.setFont(font)
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchBtn.setIconSize(QtCore.QSize(20, 20))
        self.searchBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.searchBtn.setObjectName("searchBtn")
        self.layout1.addWidget(self.searchBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout1.addItem(spacerItem3)
        self.layout1.setStretch(0, 1)
        self.layout1.setStretch(1, 1)
        self.layout1.setStretch(2, 4)
        self.layout1.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.layout1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 218, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 3)
        self.verticalLayout_2.setStretch(3, 8)
        self.stackedWidget.addWidget(self.home)
        self.vpage = QtWidgets.QWidget()
        self.vpage.setObjectName("vpage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.vpage)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.vpage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.v2homeBtn = QtWidgets.QToolButton(self.frame)
        self.v2homeBtn.setMinimumSize(QtCore.QSize(0, 32))
        self.v2homeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.v2homeBtn.setIcon(icon1)
        self.v2homeBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.v2homeBtn.setObjectName("v2homeBtn")
        self.horizontalLayout_3.addWidget(self.v2homeBtn)
        self.dlPathBtn = QtWidgets.QToolButton(self.frame)
        self.dlPathBtn.setMinimumSize(QtCore.QSize(0, 32))
        self.dlPathBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dlPathBtn.setObjectName("dlPathBtn")
        self.horizontalLayout_3.addWidget(self.dlPathBtn)
        spacerItem5 = QtWidgets.QSpacerItem(739, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.vdownloadBtn = QtWidgets.QToolButton(self.frame)
        self.vdownloadBtn.setMinimumSize(QtCore.QSize(80, 32))
        self.vdownloadBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vdownloadBtn.setObjectName("vdownloadBtn")
        self.horizontalLayout_3.addWidget(self.vdownloadBtn)
        self.dlAllBox = QtWidgets.QCheckBox(self.frame)
        self.dlAllBox.setObjectName("dlAllBox")
        self.horizontalLayout_3.addWidget(self.dlAllBox)
        self.verticalLayout_3.addWidget(self.frame)
        self.vtable = QtWidgets.QTableWidget(self.vpage)
        self.vtable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.vtable.setObjectName("vtable")
        self.vtable.setColumnCount(7)
        self.vtable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.vtable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.vtable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.vtable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.vtable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.vtable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.vtable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.vtable.setHorizontalHeaderItem(6, item)
        self.vtable.horizontalHeader().setStretchLastSection(True)
        self.vtable.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.vtable)
        self.stackedWidget.addWidget(self.vpage)
        self.ppage = QtWidgets.QWidget()
        self.ppage.setObjectName("ppage")
        self.stackedWidget.addWidget(self.ppage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MWin.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MWin)
        self.statusBar.setObjectName("statusBar")
        MWin.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MWin)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 960, 23))
        self.menuBar.setObjectName("menuBar")
        self.Setting = QtWidgets.QMenu(self.menuBar)
        self.Setting.setObjectName("Setting")
        self.About = QtWidgets.QMenu(self.menuBar)
        self.About.setObjectName("About")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MWin.setMenuBar(self.menuBar)
        self.minSizeAction = QtWidgets.QAction(MWin)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minSizeAction.setIcon(icon2)
        self.minSizeAction.setObjectName("minSizeAction")
        self.bgiPathAction = QtWidgets.QAction(MWin)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/bgm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bgiPathAction.setIcon(icon3)
        self.bgiPathAction.setObjectName("bgiPathAction")
        self.authorAction = QtWidgets.QAction(MWin)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/me.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.authorAction.setIcon(icon4)
        self.authorAction.setObjectName("authorAction")
        self.appAction = QtWidgets.QAction(MWin)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appAction.setIcon(icon5)
        self.appAction.setObjectName("appAction")
        self.downloadPathaction = QtWidgets.QAction(MWin)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/downloadpath.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadPathaction.setIcon(icon6)
        self.downloadPathaction.setObjectName("downloadPathaction")
        self.vPageAction = QtWidgets.QAction(MWin)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/v.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vPageAction.setIcon(icon7)
        self.vPageAction.setObjectName("vPageAction")
        self.pPageAction = QtWidgets.QAction(MWin)
        self.pPageAction.setIcon(icon3)
        self.pPageAction.setObjectName("pPageAction")
        self.exitAction = QtWidgets.QAction(MWin)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/car.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitAction.setIcon(icon8)
        self.exitAction.setObjectName("exitAction")
        self.Setting.addAction(self.minSizeAction)
        self.Setting.addAction(self.bgiPathAction)
        self.Setting.addAction(self.downloadPathaction)
        self.About.addAction(self.authorAction)
        self.About.addAction(self.appAction)
        self.menu.addAction(self.vPageAction)
        self.menu.addAction(self.pPageAction)
        self.menu.addAction(self.exitAction)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.Setting.menuAction())
        self.menuBar.addAction(self.About.menuAction())

        self.retranslateUi(MWin)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MWin)

    def retranslateUi(self, MWin):
        _translate = QtCore.QCoreApplication.translate
        MWin.setWindowTitle(_translate("MWin", "嗶哩嗶哩盒子©Lewis Tian"))
        self.comboBoxHome.setItemText(0, _translate("MWin", "视频"))
        self.comboBoxHome.setItemText(1, _translate("MWin", "图片"))
        self.searchBtn.setToolTip(_translate("MWin", "搜索"))
        self.searchBtn.setText(_translate("MWin", "搜索"))
        self.searchBtn.setShortcut(_translate("MWin", "Return"))
        self.v2homeBtn.setToolTip(_translate("MWin", "回首页"))
        self.v2homeBtn.setText(_translate("MWin", "首页"))
        self.v2homeBtn.setShortcut(_translate("MWin", "Ctrl+Z"))
        self.dlPathBtn.setText(_translate("MWin", "下载目录："))
        self.vdownloadBtn.setToolTip(_translate("MWin", "下载选中行的视频"))
        self.vdownloadBtn.setText(_translate("MWin", "下载"))
        self.dlAllBox.setToolTip(_translate("MWin", "下载全部视频"))
        self.dlAllBox.setText(_translate("MWin", "下载全部"))
        item = self.vtable.horizontalHeaderItem(0)
        item.setText(_translate("MWin", "#"))
        item = self.vtable.horizontalHeaderItem(1)
        item.setText(_translate("MWin", "当前分p标题"))
        item = self.vtable.horizontalHeaderItem(2)
        item.setText(_translate("MWin", "时长"))
        item = self.vtable.horizontalHeaderItem(3)
        item.setText(_translate("MWin", "大小"))
        item = self.vtable.horizontalHeaderItem(4)
        item.setText(_translate("MWin", "下载进度"))
        item = self.vtable.horizontalHeaderItem(5)
        item.setText(_translate("MWin", "切片"))
        item = self.vtable.horizontalHeaderItem(6)
        item.setText(_translate("MWin", "标题"))
        self.Setting.setTitle(_translate("MWin", "设置"))
        self.About.setTitle(_translate("MWin", "关于"))
        self.menu.setTitle(_translate("MWin", "文件"))
        self.minSizeAction.setText(_translate("MWin", "窗口最小尺寸"))
        self.minSizeAction.setShortcut(_translate("MWin", "Ctrl+M"))
        self.bgiPathAction.setText(_translate("MWin", "背景图片"))
        self.bgiPathAction.setShortcut(_translate("MWin", "Ctrl+B"))
        self.authorAction.setText(_translate("MWin", "开发者"))
        self.authorAction.setShortcut(_translate("MWin", "Alt+A"))
        self.appAction.setText(_translate("MWin", "本程序"))
        self.appAction.setShortcut(_translate("MWin", "Ctrl+H"))
        self.downloadPathaction.setText(_translate("MWin", "下载路径"))
        self.downloadPathaction.setShortcut(_translate("MWin", "Ctrl+P"))
        self.vPageAction.setText(_translate("MWin", "视频下载页"))
        self.vPageAction.setShortcut(_translate("MWin", "Ctrl+Q"))
        self.pPageAction.setText(_translate("MWin", "图片下载页"))
        self.pPageAction.setShortcut(_translate("MWin", "Ctrl+E"))
        self.exitAction.setText(_translate("MWin", "退出"))
        self.exitAction.setShortcut(_translate("MWin", "Ctrl+W"))

import res_rc
